/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  ISafeVault,
  ISafeVaultInterface,
} from "../../../contracts/interfaces/ISafeVault";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISafeVault__factory {
  static readonly abi = _abi;
  static createInterface(): ISafeVaultInterface {
    return new utils.Interface(_abi) as ISafeVaultInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISafeVault {
    return new Contract(address, _abi, signerOrProvider) as ISafeVault;
  }
}
